version: '3'
services:
  xrdp:
    build: .
    ports:
      - "3389:3389"
    volumes:
      - xrdp-root-home:/root
      - /run/user/1000/pulse/native:/run/pulse/native:ro   # optional: share host pulse socket
    restart: unless-stopped

volumes:
  xrdp-root-home: